#!/bin/bash
#Menu
echo -e ""
echo "=========================== Configuration Setup Server ========================="
echo "                           Debian Ubuntu Premium Script                            "
echo "                                 -BY SoumyMafia-                            "
echo "================================================================================"
echo -e ""
echo -e "➢ perpanjang: Perpanjang masa aktif akun ssh"
echo -e "➢ menu      : Menampilkan daftar perintah"
echo -e "➢ usernew   : Membuat akun SSH & OpenVPN"
echo -e "➢ trial     : Membuat akun trial"
echo -e "➢ hapus     : Menghapus akun SSH & OpenVPN"
echo -e "➢ cek       : Cek user login"
echo -e "➢ member    : Daftar member SSH & OpenVPN"
echo -e "➢ delete    : Delete user expired"
echo -e "➢ restart   : Restart service dropbear, webmin"
echo -e "              Squid3, OpenVPN dan SSH"
echo -e "➢ reboot    : Reboot VPS"
echo -e "➢ speedtest : Speedtest VPS"
echo -e "➢ portstat  : Cek status port"
echo -e "➢ info      : Menampilkan informasi sistem"
echo -e "➢ contact   : Menampilkan kontak penulis script"
echo -e "➢ about     : Info script auto install"
echo -e "➢ exit      : Keluar dari Putty/Connecbot/"
echo -e "              JuiceSSH"

echo "=================== Menu ShadowsocksR ========================="
echo -e ""
echo -e "➢ ssr       :  Menampilkan menu SSR"
echo -e "➢ v2ray     :  Menampilkan menu V2ray"
echo -e ""
echo "==============================================================="

echo "=========================== Menu User Limit ===================================="
echo -e "➢ limit 1     : Membatasi jumlah user MAX 1 login"
echo -e "➢ limit 2     : Membatasi jumlah user MAX 2 login"
echo -e "➢ limit stop  : Menonaktifkan fitur userlimit"
echo -e "➢ limit cek   : Cek log user yang berhasil di kill"
echo -e "➢ limit reset : Reset log user yang berhasil di kill"
echo "================================================================================"

echo -e ""
